Develop
StanislavFishkov/plus-smart-home-tech pull request #4
Opened 2024-12-18 16:38 UTC by StanislavFishkov

2024-12-19 13:24 UTC, z8q requested changes

2024-12-19 13:24 UTC, z8q commented on telemetry/analyzer/src/main/java/ru/yandex/practicum/telemetry/analyzer/service/SnapshotServiceImpl.java
> +        }
хотя у тебя там есть проверка

2024-12-19 13:24 UTC, z8q commented on telemetry/analyzer/src/main/java/ru/yandex/practicum/telemetry/analyzer/handler/hub/ScenarioRemovedHubHandler.java
> +        scenarioRepository.deleteByHubIdAndName(hubEventAvro.getHubId(), scenarioName);
тут могут оставаться conditions или actions для сценария,
возможно тоже стоит удалять

2024-12-19 13:24 UTC, z8q commented on telemetry/analyzer/src/main/java/ru/yandex/practicum/telemetry/analyzer/service/SnapshotServiceImpl.java
> +    private Instant lastHandledTimestamp = Instant.EPOCH;
может быть не очень надежно
Перезагрузится сервис, lastHandledTimestamp собьется

2024-12-19 13:34 UTC, StanislavFishkov commented on telemetry/analyzer/src/main/java/ru/yandex/practicum/telemetry/analyzer/service/SnapshotServiceImpl.java
> +        }
Это защита от повторного чтения, если offsets не закоммитились, а конкретный снэпшот уже обрабатывался. Только я глупость сделал - надо сохранять для каждого HubId время (то есть я его считаю уникальным идентификатором сообщения для снэпшота в данном случае). А в целом решил так сделать из-за фразы в задании: "Повторная обработка снапшотов, напротив, крайне нежелательна и должна быть сведена к минимуму." Исправил.

2024-12-19 13:35 UTC, StanislavFishkov commented on telemetry/analyzer/src/main/java/ru/yandex/practicum/telemetry/analyzer/handler/hub/ScenarioRemovedHubHandler.java
> +        scenarioRepository.deleteByHubIdAndName(hubEventAvro.getHubId(), scenarioName);
У меня это на уровне схемы решено, поэтому тут отдельно не удаляю зависимые сущности:
``` SQL
scenario_id BIGINT REFERENCES scenarios(id) ON DELETE CASCADE,

2024-12-20 11:50 UTC, z8q approved these changes

2024-12-23 12:27 UTC, merged